32/app title
graasp/graasp-app-thermal-radiation pull request #34
Opened 2021-03-05 13:41 UTC by pyphilia

close #29
close #30
close #31
close #32
close #33

2021-03-05 23:09 UTC, juancarlosfarah requested changes
Looks good. Just a quick question about the params.

2021-03-05 23:09 UTC, juancarlosfarah commented on src/actions/action.js
> +    const url = `//${apiHost + ACTIONS_ENDPOINT}?${Qs.stringify({
I think this is wrong. We should probably be pushing the current space into the spaceId array of params. Does that make sense?

2021-03-08 09:38 UTC, pyphilia commented
@juancarlosfarah That's actually what was done before, but it seems that since it was a default value, it was not provided back. I changed the process to actually apply `spaceId` to `params` in my new commit (it should be cleaner but let me know).

2021-03-09 09:07 UTC, hagoptaminian approved these changes
Looks good to me. You might want to rename the two occurrences of _Graasp App_ in `manifest.json` as well.

2021-03-12 23:16 UTC, juancarlosfarah approved these changes

2021-03-12 23:16 UTC, merged